apiVersion: apps/v1
kind: Deployment
metadata:
    name: qxj-demo
    namespace: @namespace@
    labels:
       app: qxj-demo
spec:
    replicas: 2
    selector:
       matchLabels:
          app: qxj-demo
    template:
       metadata:
           name: qxj-demo
           labels:
              app: qxj-demo
       spec:
           containers:
              - name: qxj-demo
                image: @image@
                imagePullPolicy: IfNotPresent
                ports:
                  - containerPort: 8888
