apiVersion: v1
kind: Service
metadata:
    name: qxj-demo
    namespace: @namespace@
spec:
    selector:
        app: qxj-demo
    ports:
     - name: qxj-demo-port
       port: 8888
       nodePort: 30888
    type: NodePort
